---
abstract: 'Use a RDF::Trine::Model for the returned RDF graph'
author:
  - 'Kjetil Kjernsmo <kjetilk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::Exception: 0
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RDF-RDFa-Parser-Trine
no_index:
  directory:
    - inc
    - t
requires:
  RDF::RDFa::Parser: 0.04
  RDF::Trine: 0.111
resources:
  license: http://dev.perl.org/licenses/
version: 0.1
